name: nakama
data_dir: "/nakama/data"

logger:
  level: "DEBUG"
  stdout: true
  file: "/nakama/data/nakama.log"

database:
  address:
    - "nakama-db:26257"
  username: "root"
  password: ""
  database: "nakama"
  ssl_mode: "disable"
  max_open_conns: 0
  max_idle_conns: 0
  conn_max_lifetime_ms: 0

socket:
  server_key: "defaultkey"
  port: 7350
  protocol: "tcp"

console:
  username: "admin"
  password: "password"
  signing_key: "defaultsigningkey"
  read_only: false

runtime:
  go:
    path: "go"
